// Code generated by mfd-generator v0.4.4; DO NOT EDIT.

//nolint:all
//lint:file-ignore U1000 ignore unused code, it's generated
package db

import (
	"unicode/utf8"
)

const (
	ErrEmptyValue = "empty"
	ErrMaxLength  = "len"
	ErrWrongValue = "value"
)

func (c Category) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(c.Title) > 255 {
		errors[Columns.Category.Title] = ErrMaxLength
	}

	if utf8.RuneCountInString(c.Alias) > 255 {
		errors[Columns.Category.Alias] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (n News) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(n.Title) > 255 {
		errors[Columns.News.Title] = ErrMaxLength
	}

	if utf8.RuneCountInString(n.Foreword) > 1024 {
		errors[Columns.News.Foreword] = ErrMaxLength
	}

	if utf8.RuneCountInString(n.Author) > 64 {
		errors[Columns.News.Author] = ErrMaxLength
	}

	return errors, len(errors) == 0
}

func (t Tag) Validate() (errors map[string]string, valid bool) {
	errors = map[string]string{}

	if utf8.RuneCountInString(t.Title) > 128 {
		errors[Columns.Tag.Title] = ErrMaxLength
	}

	return errors, len(errors) == 0
}
