-- =============================================================================
-- Diagram Name: Noname3
-- Created on: 17.07.2024 12:39:01
-- Diagram Version: 
-- =============================================================================


CREATE TABLE "news" (
	"newsId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"categoryId" int4 NOT NULL,
	"foreword" varchar(1024) NOT NULL,
	"content" text,
	"tagIds" int4[] NOT NULL DEFAULT '{}',
	"author" varchar(64) NOT NULL,
	"publishedAt" timestamp with time zone NOT NULL,
	"statusId" int4 NOT NULL,
	PRIMARY KEY("newsId")
);

CREATE TABLE "categories" (
	"categoryId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(255) NOT NULL,
	"orderNumber" int4,
	"alias" varchar(255) NOT NULL,
	"statusId" int4 NOT NULL,
	PRIMARY KEY("categoryId")
);

CREATE TABLE "tags" (
	"tagId" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	"title" varchar(128) NOT NULL,
	"statusId" int4 NOT NULL,
	PRIMARY KEY("tagId")
);

CREATE TABLE "statuses" (
	"statusId" int4 NOT NULL,
	"title" varchar(64) NOT NULL,
	PRIMARY KEY("statusId")
);


ALTER TABLE "news" ADD CONSTRAINT "Ref_News_to_Status" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "news" ADD CONSTRAINT "Ref_News_to_Category" FOREIGN KEY ("categoryId")
	REFERENCES "categories"("categoryId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "categories" ADD CONSTRAINT "Ref_Category_to_Status" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;

ALTER TABLE "tags" ADD CONSTRAINT "Ref_Tag_to_Status" FOREIGN KEY ("statusId")
	REFERENCES "statuses"("statusId")
	MATCH SIMPLE
	ON DELETE NO ACTION
	ON UPDATE NO ACTION
	NOT DEFERRABLE;


